CREATE SCHEMA IF NOT EXISTS auth;
SET search_path TO auth;

DROP TABLE IF EXISTS auth.auth_user_provider;
DROP TABLE IF EXISTS auth.auth_client;
DROP TABLE IF EXISTS auth.auth_user;
DROP TABLE IF EXISTS auth.auth_admin;

CREATE TABLE auth.auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    display_name TEXT,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE auth.auth_user_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    login_key TEXT NOT NULL,
    provider_type TEXT NOT NULL,
    provider_data JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE auth.auth_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT,
    secret TEXT,
    domain TEXT,
    scopes TEXT[],
    token_type TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE auth.auth_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ
);
